// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PasteFromJsonToClassObject
{
    internal sealed partial class Vsix
    {
        public const string Id = "PasteFromJsonToClassObject.4dc0b045-ad2a-4706-ba64-d2c8ee2eb0b2";
        public const string Name = "PasteFromJsonToClassObject";
        public const string Description = @"Pastes Json from clipboard as C# classes";
        public const string Language = "en-US";
        public const string Version = "1.0.1.0";
        public const string Author = "Vlad Gaman";
        public const string Tags = "";
    }
}
