// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PasteFromJsonToClassObject
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PasteFromJsonToClassObjectString = "de06d02f-09d5-41b2-88d3-025c94172780";
        public static Guid PasteFromJsonToClassObject = new Guid(PasteFromJsonToClassObjectString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SpecialPasteJsonMenuGroup = 0x0001;
        public const int SpecialPasteJsonCommand = 0x0100;
    }
}